In [1]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,100,size=(50,5))
scores_df = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index=range(1,51))
scores_df
sum_values = scores_df.sum(axis=1)
mean_values = scores_df.mean(axis=1)
scores_df['總分'] = sum_values
scores_df['平均'] = mean_values

In [15]:
scores_df.sort_values(by='總分',ascending=False).iloc[-5:]

    國文  英文  數學  地理  歷史   總分    平均
9   58  56  72  80  57  323  64.6
15  66  59  55  75  66  321  64.2
17  56  50  55  97  52  310  62.0
44  67  59  65  66  50  307  61.4
38  59  60  76  58  52  305  61.0

In [30]:
#使用subscript[],過濾資料
scores_df[scores_df['平均'] < 80]

    國文  英文  數學  地理  歷史   總分    平均
2   90  82  61  71  87  391  78.2
3   89  55  90  92  60  386  77.2
4   95  52  78  67  95  387  77.4
6   70  69  91  73  86  389  77.8
7   67  88  62  81  96  394  78.8
8   64  76  54  79  61  334  66.8
9   58  56  72  80  57  323  64.6
10  89  60  90  51  94  384  76.8
11  76  56  64  85  75  356  71.2
12  73  87  84  51  56  351  70.2
14  73  73  96  69  72  383  76.6
15  66  59  55  75  66  321  64.2
16  81  69  70  82  56  358  71.6
17  56  50  55  97  52  310  62.0
18  51  69  50  95  60  325  65.0
19  65  76  71  88  82  382  76.4
20  71  58  55  61  91  336  67.2
21  74  64  61  52  83  334  66.8
22  58  66  92  60  91  367  73.4
24  79  53  65  65  81  343  68.6
26  64  54  89  77  83  367  73.4
27  70  90  53  83  62  358  71.6
31  72  90  52  68  76  358  71.6
33  80  83  78  62  93  396  79.2
36  57  83  61  75  84  360  72.0
38  59  60  76  58  52  305  61.0
39  95  89  57  88  50  379  75.8
40  52  88  85  52  62  339  67.8
41  98  50  58  59  75  340  68.0
42  53  53  79  68  81  334  66.8
43  88  96  81  51  83  399  79.8
44  67  59  65  66  50  307  61.4
45  53  83  76  81  58  351  70.2
46  73  60  90  63  58  344  68.8
47  83  79  62  64  95  383  76.6
48  93  87  52  60  92  384  76.8
49  56  56  81  55  82  330  66.0
50  68  84  80  82  62  376  75.2

In [32]:
#使用subscript[]的搜尋方式
#平均80以下,歷史不及格的
scores_df[(scores_df['平均'] < 80) & (scores_df['歷史'] < 60)]

    國文  英文  數學  地理  歷史   總分    平均
9   58  56  72  80  57  323  64.6
12  73  87  84  51  56  351  70.2
16  81  69  70  82  56  358  71.6
17  56  50  55  97  52  310  62.0
38  59  60  76  58  52  305  61.0
39  95  89  57  88  50  379  75.8
44  67  59  65  66  50  307  61.4
45  53  83  76  81  58  351  70.2
46  73  60  90  63  58  344  68.8

In [33]:
#使用query()的搜尋
scores_df.query('平均<80')

    國文  英文  數學  地理  歷史   總分    平均
2   90  82  61  71  87  391  78.2
3   89  55  90  92  60  386  77.2
4   95  52  78  67  95  387  77.4
6   70  69  91  73  86  389  77.8
7   67  88  62  81  96  394  78.8
8   64  76  54  79  61  334  66.8
9   58  56  72  80  57  323  64.6
10  89  60  90  51  94  384  76.8
11  76  56  64  85  75  356  71.2
12  73  87  84  51  56  351  70.2
14  73  73  96  69  72  383  76.6
15  66  59  55  75  66  321  64.2
16  81  69  70  82  56  358  71.6
17  56  50  55  97  52  310  62.0
18  51  69  50  95  60  325  65.0
19  65  76  71  88  82  382  76.4
20  71  58  55  61  91  336  67.2
21  74  64  61  52  83  334  66.8
22  58  66  92  60  91  367  73.4
24  79  53  65  65  81  343  68.6
26  64  54  89  77  83  367  73.4
27  70  90  53  83  62  358  71.6
31  72  90  52  68  76  358  71.6
33  80  83  78  62  93  396  79.2
36  57  83  61  75  84  360  72.0
38  59  60  76  58  52  305  61.0
39  95  89  57  88  50  379  75.8
40  52  88  85  52  62  339  67.8
41  98  50  58  59  75  340  68.0
42  53  53  79  68  81  334  66.8
43  88  96  81  51  83  399  79.8
44  67  59  65  66  50  307  61.4
45  53  83  76  81  58  351  70.2
46  73  60  90  63  58  344  68.8
47  83  79  62  64  95  383  76.6
48  93  87  52  60  92  384  76.8
49  56  56  81  55  82  330  66.0
50  68  84  80  82  62  376  75.2

In [34]:
scores_df.query('平均<80 and 歷史<60')

    國文  英文  數學  地理  歷史   總分    平均
9   58  56  72  80  57  323  64.6
12  73  87  84  51  56  351  70.2
16  81  69  70  82  56  358  71.6
17  56  50  55  97  52  310  62.0
38  59  60  76  58  52  305  61.0
39  95  89  57  88  50  379  75.8
44  67  59  65  66  50  307  61.4
45  53  83  76  81  58  351  70.2
46  73  60  90  63  58  344  68.8