In [1]:
import numpy as np
import pandas as pd

scores = np.random.randint(40, high=101, size=(50,5))
scores_df = pd.DataFrame(scores,
    columns=['國文','英文','數學','地理','歷史'],
    index=range(1,51))
scores_df.index.name="學號"
scores_df.columns.name="科目"
sum_series = scores_df.sum(axis=1)
mean_series = scores_df.mean(axis=1)
#display(sum_series)
rank_series = sum_series.rank(method='min',ascending=False)
scores_df["總分"] = sum_series
scores_df["平均"] = mean_series
scores_df["名次"] = rank_series
scores_df.sort_values(by='名次')

科目   國文   英文   數學   地理   歷史   總分    平均    名次
學號
39   96   97   97   82   74  446  89.2   1.0
44  100   76   95   82   89  442  88.4   2.0
45   88   65  100   57  100  410  82.0   3.0
33  100   59  100   59   91  409  81.8   4.0
46   91   94   46   88   90  409  81.8   4.0
16   48   85   92  100   83  408  81.6   6.0
34   86   98   51   92   81  408  81.6   6.0
14   90   95   67   56   98  406  81.2   8.0
24   96   57   78   86   85  402  80.4   9.0
29   88   93   52   96   71  400  80.0  10.0
10   84   80   56   92   88  400  80.0  10.0
7    68   83   79   83   87  400  80.0  10.0
28   70   64   77   96   92  399  79.8  13.0
18   74   97   83  100   43  397  79.4  14.0
26   70   79   59   90   90  388  77.6  15.0
36   54   70   98   76   88  386  77.2  16.0
31   89   97   62   77   59  384  76.8  17.0
40   92   94   71   60   61  378  75.6  18.0
35   77   52   53   99   90  371  74.2  19.0
23   76   77   85   88   44  370  74.0  20.0
19   62   76   91   58   82  369  73.8  21.0
5    46  100   63   57  100  366  73.2  22.0
17   46   93   68   87   66  360  72.0  23.0
27   87   56   74   86   50  353  70.6  24.0
41   55   96   70   88   42  351  70.2  25.0
30   68   82   64   63   74  351  70.2  25.0
11   96   66   48   99   40  349  69.8  27.0
48   84   78   59   76   51  348  69.6  28.0
50   99   59   90   51   48  347  69.4  29.0
8    95   41   50   63   96  345  69.0  30.0
20   75   49   87   41   92  344  68.8  31.0
49   45   79   73   73   72  342  68.4  32.0
22   57   78   50   86   69  340  68.0  33.0
12   56   53   82   52   95  338  67.6  34.0
6    78   74   66   71   49  338  67.6  34.0
1    53   60   73   49  100  335  67.0  36.0
21   61   75   79   42   77  334  66.8  37.0
43   66  100   47   40   75  328  65.6  38.0
32   46   80   76   67   57  326  65.2  39.0
9    99   42   50   84   49  324  64.8  40.0
15   56   47  100   74   46  323  64.6  41.0
25   42   89   62   74   55  322  64.4  42.0
42   73   52   47   94   54  320  64.0  43.0
2    96   77   42   57   44  316  63.2  44.0
37   71   40   63   91   50  315  63.0  45.0
47   90   63   44   64   50  311  62.2  46.0
3    44   67   62   49   80  302  60.4  47.0
4    56   49   48   59   85  297  59.4  48.0
38   41   97   47   63   48  296  59.2  49.0
13   68   44   42   42   62  258  51.6  50.0

In [5]:
display(scores_df.iloc[:3])
new_df = scores_df.iloc[:3].copy()
new_df["不及格"] = pd.Series([1,0,2],index=[1,2,3])
new_df

科目  國文  英文  數學  地理   歷史   總分    平均    名次
學號
1   53  60  73  49  100  335  67.0  36.0
2   96  77  42  57   44  316  63.2  44.0
3   44  67  62  49   80  302  60.4  47.0

科目  國文  英文  數學  地理   歷史   總分    平均    名次  不及格
學號
1   53  60  73  49  100  335  67.0  36.0    1
2   96  77  42  57   44  316  63.2  44.0    0
3   44  67  62  49   80  302  60.4  47.0    2

In [14]:
def fun3(series:pd.Series) -> int:
    return series[series<=60].count()

less60Count = scores_df[['國文','英文','數學','地理','歷史']].apply(fun3,axis=1)
less60Count

學號
1     3
2     3
3     2
4     4
5     2
6     1
7     0
8     2
9     3
10    1
11    2
12    3
13    3
14    1
15    3
16    1
17    1
18    1
19    1
20    2
21    1
22    2
23    1
24    1
25    2
26    1
27    2
28    0
29    1
30    0
31    1
32    2
33    2
34    1
35    2
36    1
37    2
38    3
39    0
40    1
41    2
42    3
43    2
44    0
45    1
46    1
47    2
48    2
49    1
50    3
dtype: int64

In [16]:
scores_df["不及格"] = less60Count
scores_df

科目   國文   英文   數學   地理   歷史   總分    平均    名次  不及格
學號
1    53   60   73   49  100  335  67.0  36.0    3
2    96   77   42   57   44  316  63.2  44.0    3
3    44   67   62   49   80  302  60.4  47.0    2
4    56   49   48   59   85  297  59.4  48.0    4
5    46  100   63   57  100  366  73.2  22.0    2
6    78   74   66   71   49  338  67.6  34.0    1
7    68   83   79   83   87  400  80.0  10.0    0
8    95   41   50   63   96  345  69.0  30.0    2
9    99   42   50   84   49  324  64.8  40.0    3
10   84   80   56   92   88  400  80.0  10.0    1
11   96   66   48   99   40  349  69.8  27.0    2
12   56   53   82   52   95  338  67.6  34.0    3
13   68   44   42   42   62  258  51.6  50.0    3
14   90   95   67   56   98  406  81.2   8.0    1
15   56   47  100   74   46  323  64.6  41.0    3
16   48   85   92  100   83  408  81.6   6.0    1
17   46   93   68   87   66  360  72.0  23.0    1
18   74   97   83  100   43  397  79.4  14.0    1
19   62   76   91   58   82  369  73.8  21.0    1
20   75   49   87   41   92  344  68.8  31.0    2
21   61   75   79   42   77  334  66.8  37.0    1
22   57   78   50   86   69  340  68.0  33.0    2
23   76   77   85   88   44  370  74.0  20.0    1
24   96   57   78   86   85  402  80.4   9.0    1
25   42   89   62   74   55  322  64.4  42.0    2
26   70   79   59   90   90  388  77.6  15.0    1
27   87   56   74   86   50  353  70.6  24.0    2
28   70   64   77   96   92  399  79.8  13.0    0
29   88   93   52   96   71  400  80.0  10.0    1
30   68   82   64   63   74  351  70.2  25.0    0
31   89   97   62   77   59  384  76.8  17.0    1
32   46   80   76   67   57  326  65.2  39.0    2
33  100   59  100   59   91  409  81.8   4.0    2
34   86   98   51   92   81  408  81.6   6.0    1
35   77   52   53   99   90  371  74.2  19.0    2
36   54   70   98   76   88  386  77.2  16.0    1
37   71   40   63   91   50  315  63.0  45.0    2
38   41   97   47   63   48  296  59.2  49.0    3
39   96   97   97   82   74  446  89.2   1.0    0
40   92   94   71   60   61  378  75.6  18.0    1
41   55   96   70   88   42  351  70.2  25.0    2
42   73   52   47   94   54  320  64.0  43.0    3
43   66  100   47   40   75  328  65.6  38.0    2
44  100   76   95   82   89  442  88.4   2.0    0
45   88   65  100   57  100  410  82.0   3.0    1
46   91   94   46   88   90  409  81.8   4.0    1
47   90   63   44   64   50  311  62.2  46.0    2
48   84   78   59   76   51  348  69.6  28.0    2
49   45   79   73   73   72  342  68.4  32.0    1
50   99   59   90   51   48  347  69.4  29.0    3